
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DBConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source = tuhaoquna.com;Initial Catalog = TuHaoQuNa;User Id = tuhaoquna;Password = !@#QAZwsx;`
//     Schema:                 ``
//     Include Views:          `False`

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace TuHaoQuNa.Repository
{
	public partial class DBConnection : Database
	{
		public DBConnection() 
			: base("DBConnection")
		{
			CommonConstruct();
		}

		public DBConnection(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			DBConnection GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static DBConnection GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			//else
			//	return new DBConnection();
			return _instance = new DBConnection();
        }

		[ThreadStatic] static DBConnection _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        
		public class Record<T> where T:new()
		{
			public static DBConnection repo { get { return DBConnection.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }
			public void Save() { repo.Save(this); }
			public int Update() { return repo.Update(this); }
			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static bool Exists(string sql, params object[] args) { return repo.Exists<T>(sql, args); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }
		}
	}
	

    /// <summary>
    /// 电影类型
    /// </summary>  
	[TableName("dbo.Category")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Category_Repository : DBConnection.Record<Category_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
		/// <summary>
		/// 筛选时类型ID
		/// </summary>  
		[Column] public int? FID { get; set; }
	}
    /// <summary>
    /// 名人
    /// </summary>  
	[TableName("dbo.Celebrity")]
	[PrimaryKey("ID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Celebrity_Repository : DBConnection.Record<Celebrity_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// Guid
		/// </summary>  
		[Column] public string Guid { get; set; }
		/// <summary>
		/// 豆瓣ID
		/// </summary>  
		[Column] public string DouBanID { get; set; }
		/// <summary>
		/// IMDbID
		/// </summary>  
		[Column] public string IMDbID { get; set; }
		/// <summary>
		/// 姓名
		/// </summary>  
		[Column] public string Name { get; set; }
		/// <summary>
		/// 性别
		/// </summary>  
		[Column] public bool? Gender { get; set; }
		/// <summary>
		/// 星座
		/// </summary>  
		[Column] public string Constellation { get; set; }
		/// <summary>
		/// 生日
		/// </summary>  
		[Column] public DateTime? Birthday { get; set; }
		/// <summary>
		/// 出生地
		/// </summary>  
		[Column] public string Homeplace { get; set; }
		/// <summary>
		/// 照片
		/// </summary>  
		[Column] public string Photo { get; set; }
		/// <summary>
		/// 简介
		/// </summary>  
		[Column] public string Describe { get; set; }
	}
    /// <summary>
    /// 名人姓名
    /// </summary>  
	[TableName("dbo.CelebrityMoreName")]
	[PrimaryKey("CelebrityID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class CelebrityMoreName_Repository : DBConnection.Record<CelebrityMoreName_Repository>  
    {
		/// <summary>
		/// 名人ID
		/// </summary>  
		[Column] public int CelebrityID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
		/// <summary>
		/// 中文名或外文名
		/// </summary>  
		[Column] public int Language { get; set; }
	}
    /// <summary>
    /// 国家
    /// </summary>  
	[TableName("dbo.Country")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Country_Repository : DBConnection.Record<Country_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
	}
    /// <summary>
    /// 语言
    /// </summary>  
	[TableName("dbo.Language")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Language_Repository : DBConnection.Record<Language_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
	}
    /// <summary>
    /// 磁力
    /// </summary>  
	[TableName("dbo.Magnet")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Magnet_Repository : DBConnection.Record<Magnet_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// Guid
		/// </summary>  
		[Column] public string Guid { get; set; }
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 标题
		/// </summary>  
		[Column] public string Title { get; set; }
		/// <summary>
		/// 磁力链接
		/// </summary>  
		[Column] public string MagnetURI { get; set; }
		/// <summary>
		/// 大小
		/// </summary>  
		[Column] public decimal? Size { get; set; }
		/// <summary>
		/// 清晰度
		/// </summary>  
		[Column] public string Clear { get; set; }
		/// <summary>
		/// 描述
		/// </summary>  
		[Column] public string Meta { get; set; }
		/// <summary>
		/// 来源
		/// </summary>  
		[Column] public string Source { get; set; }
		/// <summary>
		/// 创建时间
		/// </summary>  
		[Column] public DateTime? CreateTime { get; set; }
	}
    /// <summary>
    /// 电影名称
    /// </summary>  
	[TableName("dbo.MoreName")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class MoreName_Repository : DBConnection.Record<MoreName_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
	}
    /// <summary>
    /// 电影
    /// </summary>  
	[TableName("dbo.Movie")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Movie_Repository : DBConnection.Record<Movie_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// Guid
		/// </summary>  
		[Column] public string Guid { get; set; }
		/// <summary>
		/// 豆瓣ID
		/// </summary>  
		[Column] public string DouBanID { get; set; }
		/// <summary>
		/// IMDbID
		/// </summary>  
		[Column] public string IMDbID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
		/// <summary>
		/// 标题
		/// </summary>  
		[Column] public string Title { get; set; }
		/// <summary>
		/// 片长
		/// </summary>  
		[Column] public int? LongTime { get; set; }
		/// <summary>
		/// 评分
		/// </summary>  
		[Column] public decimal? Score { get; set; }
		/// <summary>
		/// 简介
		/// </summary>  
		[Column] public string Describe { get; set; }
		/// <summary>
		/// 1电影,2电视剧
		/// </summary>  
		[Column] public int Family { get; set; }
		/// <summary>
		/// 封面
		/// </summary>  
		[Column] public string Poster { get; set; }
		/// <summary>
		/// 播放次数
		/// </summary>  
		[Column] public int? PlayCount { get; set; }
		/// <summary>
		/// 热度
		/// </summary>  
		[Column] public int? Hot { get; set; }
		/// <summary>
		/// 浏览次数
		/// </summary>  
		[Column] public int? Glance { get; set; }
		/// <summary>
		/// 上映时间
		/// </summary>  
		[Column] public DateTime? ReleaseDate { get; set; }
		/// <summary>
		/// 创建时间
		/// </summary>  
		[Column] public DateTime? CreateTime { get; set; }
		/// <summary>
		/// 最后操作时间
		/// </summary>  
		[Column] public DateTime? LastTime { get; set; }
	}
    /// <summary>
    /// 职业
    /// </summary>  
	[TableName("dbo.Occupation")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Occupation_Repository : DBConnection.Record<Occupation_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// 职业名称
		/// </summary>  
		[Column] public string Name { get; set; }
	}
    /// <summary>
    /// 播放地址
    /// </summary>  
	[TableName("dbo.Player")]
	[PrimaryKey("ID")]
	[ExplicitColumns]
    public partial class Player_Repository : DBConnection.Record<Player_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// Guid
		/// </summary>  
		[Column] public string Guid { get; set; }
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 名称
		/// </summary>  
		[Column] public string Name { get; set; }
		/// <summary>
		/// 平台
		/// </summary>  
		[Column] public string Platform { get; set; }
		/// <summary>
		/// 标识ID
		/// </summary>  
		[Column] public string VID { get; set; }
		/// <summary>
		/// 播放地址
		/// </summary>  
		[Column] public string PlayerUrl { get; set; }
		/// <summary>
		/// 需要Vip
		/// </summary>  
		[Column] public int? HasVip { get; set; }
		/// <summary>
		/// 集数
		/// </summary>  
		[Column] public int? Episodes { get; set; }
		/// <summary>
		/// 描述
		/// </summary>  
		[Column] public string Description { get; set; }
		/// <summary>
		/// 创建时间
		/// </summary>  
		[Column] public DateTime? CreateTime { get; set; }
	}
    /// <summary>
    /// 电影类型关系
    /// </summary>  
	[TableName("dbo.Relation_Category")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Category_Repository : DBConnection.Record<Relation_Category_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 类型ID
		/// </summary>  
		[Column] public int CategoryID { get; set; }
	}
    /// <summary>
    /// 电影国家关系
    /// </summary>  
	[TableName("dbo.Relation_Country")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Country_Repository : DBConnection.Record<Relation_Country_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 国家ID
		/// </summary>  
		[Column] public int CountryID { get; set; }
	}
    /// <summary>
    /// 电影导演关系表
    /// </summary>  
	[TableName("dbo.Relation_Director")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Director_Repository : DBConnection.Record<Relation_Director_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 名人ID
		/// </summary>  
		[Column] public int CelebrityID { get; set; }
	}
    /// <summary>
    /// 电影语言关系
    /// </summary>  
	[TableName("dbo.Relation_Language")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Language_Repository : DBConnection.Record<Relation_Language_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 语言ID
		/// </summary>  
		[Column] public int LanguageID { get; set; }
	}
    /// <summary>
    /// 名人职业关系
    /// </summary>  
	[TableName("dbo.Relation_Occupation")]
	[PrimaryKey("CelebrityID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Occupation_Repository : DBConnection.Record<Relation_Occupation_Repository>  
    {
		/// <summary>
		/// 名人ID
		/// </summary>  
		[Column] public int CelebrityID { get; set; }
		/// <summary>
		/// 职业ID
		/// </summary>  
		[Column] public int OccupationID { get; set; }
	}
    /// <summary>
    /// 电影演员关系
    /// </summary>  
	[TableName("dbo.Relation_Performer")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Performer_Repository : DBConnection.Record<Relation_Performer_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 名人ID
		/// </summary>  
		[Column] public int CelebrityID { get; set; }
	}
    /// <summary>
    /// 电影编剧
    /// </summary>  
	[TableName("dbo.Relation_Screenwriter")]
	[PrimaryKey("MovieID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Relation_Screenwriter_Repository : DBConnection.Record<Relation_Screenwriter_Repository>  
    {
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 编剧ID
		/// </summary>  
		[Column] public int CelebrityID { get; set; }
	}
    /// <summary>
    /// 字幕
    /// </summary>  
	[TableName("dbo.Subtitle")]
	[PrimaryKey("ID", AutoIncrement=false)]
	[ExplicitColumns]
    public partial class Subtitle_Repository : DBConnection.Record<Subtitle_Repository>  
    {
		/// <summary>
		/// ID
		/// </summary>  
		[Column] public int ID { get; set; }
		/// <summary>
		/// Guid
		/// </summary>  
		[Column] public string Guid { get; set; }
		/// <summary>
		/// 电影ID
		/// </summary>  
		[Column] public int MovieID { get; set; }
		/// <summary>
		/// 标题
		/// </summary>  
		[Column] public string Title { get; set; }
		/// <summary>
		/// 下载地址
		/// </summary>  
		[Column] public string Download { get; set; }
		/// <summary>
		/// 清晰度
		/// </summary>  
		[Column] public string Clear { get; set; }
		/// <summary>
		/// 大小
		/// </summary>  
		[Column] public decimal? Size { get; set; }
		/// <summary>
		/// 语言
		/// </summary>  
		[Column] public string Language { get; set; }
		/// <summary>
		/// 描述
		/// </summary>  
		[Column] public string Meta { get; set; }
		/// <summary>
		/// 来源
		/// </summary>  
		[Column] public string Source { get; set; }
		/// <summary>
		/// 格式
		/// </summary>  
		[Column] public string Format { get; set; }
		/// <summary>
		/// 创建时间
		/// </summary>  
		[Column] public DateTime? CreateTime { get; set; }
	}
}
